### ISSUE TITLE
adding tests

### ISSUE THREAD

**Issue by jibaku** [empierre/domoticz_linky#12]
I would like to add tests but I currently does not have a Linky. Is it possible to add some files from each endpoints of Enedis API ?

**Comment by empierre** [comment]
Just added some data

**Comment by jibaku** [comment]
Is it files from the API or the files generated by the script?

**Comment by empierre** [comment]
This is generated, the os called api is a web page...

Le mer. 28 mars 2018 à 12:27, Fabien Schwob <notifications@github.com> a
écrit :
