### ISSUE TITLE
Problem with hourly data

### ISSUE THREAD

**Issue by ooii** [empierre/domoticz_linky#17]
Hi,

I use this plugin since yesterday.
When I run `./domoticz_linky.sh` the output is the following:
```
Error: near line 1: near "Exception": syntax error
Error: near line 34: cannot commit - no transaction is active
Error: near line 35: near "Exception": syntax error
Error: near line 68: cannot commit - no transaction is active
```
When looking to the command logs, I have the right data. But the *hourly* data displayed in domoticz is wrong. No issue with daily, monthly, or yearly data.
For instance, here is the data I get in the logs when I execute the command in the terminal:
```
{
	"time": "22:00",
	"conso": 0.57
}, {
	"time": "22:30",
	"conso": 2.534
}, {
	"time": "23:00",
	"conso": 2.796
}, {
	"time": "23:30",
	"conso": 2.246
}
```

and that's coherent with data in my `enedis` acount as you can see:
![enedis](https://snag.gy/eSg2ID.jpg)
but not with what's in domoticz:
![domoticz](https://snag.gy/5x29Im.jpg)

Any idea what's the issue?
I'm running commit `eeecbd8b38f2b799b2e8657463b58819a1b5b786` under Ubuntu 16.04 LTS and domoticz `v4.9701`.

Thanks a lot.

**Comment by LudovicRousseau** [comment]
Maybe your problem is related to https://github.com/empierre/domoticz_linky/issues/13
